/**
 * MDX file generation for registered components.
 *
 * Emits Fumadocs-compatible MDX with YAML frontmatter containing all 11 schema
 * fields, followed by a structured body. Output paths mirror the content tree at
 * `site/content/registry/{atomicLevel}/{kebab-name}.mdx`.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { stringify as yamlStringify } from 'yaml';
import type { RegistryComponent } from './types.js';

/**
 * Convert a PascalCase or camelCase name to kebab-case.
 * Examples: "CoursewareSearch" → "courseware-search", "Button" → "button"
 */
function toKebabCase(name: string): string {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z\d])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

/**
 * Generate the relative MDX output path and file content for a component.
 *
 * @returns `{ path, content }` where `path` is relative (e.g. `molecule/course-tab-link.mdx`)
 */
export function generateMdx(component: RegistryComponent): { path: string; content: string } {
  const kebabName = toKebabCase(component.name);
  const relativePath = `${component.atomicLevel}/${kebabName}.mdx`;

  // Build frontmatter object — preserve field order matching button.mdx example.
  const frontmatterObj: Record<string, unknown> = {
    title: component.name,
    name: component.name,
    atomicLevel: component.atomicLevel,
    status: component.status,
    sourceMfe: component.sourceMfe,
    sourceRepo: component.sourceRepo,
    sourcePath: component.sourcePath,
    version: component.version,
    figmaCodeConnectUrl: component.figmaCodeConnectUrl,
    consumers: component.consumers,
    a11y: component.a11y,
    lastIngested: component.lastIngested,
  };

  const frontmatter = yamlStringify(frontmatterObj, {
    defaultStringType: 'QUOTE_DOUBLE',
    defaultKeyType: 'PLAIN',
    lineWidth: 0,
  }).trimEnd();

  // Build Consumers section body.
  const consumersBody =
    component.consumers.length > 0
      ? component.consumers.map((c) => `- ${c}`).join('\n')
      : 'No registered consumers yet.';

  // Build Figma section body.
  const figmaBody =
    component.figmaCodeConnectUrl != null
      ? `[View in Figma Code Connect](${component.figmaCodeConnectUrl})`
      : 'Not yet linked to Figma.';

  const content = `---
${frontmatter}
---

# ${component.name}

Registered from \`${component.sourceRepo}\` at \`${component.sourcePath}\`.

## Consumers

${consumersBody}

## Figma

${figmaBody}

## Status

| Field | Value |
|---|---|
| Status | \`${component.status}\` |
| Accessibility | \`${component.a11y}\` |
| Version | \`${component.version}\` |
| Last Ingested | \`${component.lastIngested}\` |

{/* TODO: ADR-0001 — Sandpack live preview will render here once the Preview integration ships */}
{/* TODO: PropsTable will render here once the react-docgen pipeline ships (Phase 2b) */}

{/* generated by @openedx-design-system/crawler */}
`;

  return { path: relativePath, content };
}

/**
 * Write a component's MDX file to disk.
 *
 * @param outputDir Absolute path to the `site/content/registry` directory.
 * @param component The registry component to emit.
 * @returns         The absolute path of the file written.
 */
export async function writeMdx(outputDir: string, component: RegistryComponent): Promise<string> {
  const { path: relativePath, content } = generateMdx(component);
  const absolutePath = resolve(outputDir, relativePath);

  await mkdir(dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, content, 'utf-8');

  return absolutePath;
}
