/**
 * Tests for src/generate.ts
 *
 * Uses the node:test runner (Node 20+). All tests are in-memory — no disk I/O.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generateMdx } from '../src/generate.js';
import type { RegistryComponent } from '../src/types.js';

const sampleMolecule: RegistryComponent = {
  name: 'CourseCard',
  atomicLevel: 'molecule',
  status: 'stable',
  sourceMfe: 'frontend-app-learning',
  sourceRepo: 'openedx/frontend-app-learning',
  sourcePath: 'src/course-home/CourseCard.jsx',
  version: '5.0.0',
  figmaCodeConnectUrl: null,
  consumers: ['frontend-app-authoring', 'frontend-app-discussions'],
  a11y: 'AA',
  lastIngested: '2026-05-19T00:00:00Z',
};

const sampleAtom: RegistryComponent = {
  name: 'Button',
  atomicLevel: 'atom',
  status: 'stable',
  sourceMfe: 'paragon',
  sourceRepo: 'openedx/paragon',
  sourcePath: 'src/Button/index.jsx',
  version: '22.4.0',
  figmaCodeConnectUrl: 'https://figma.com/design/abc123?nodeId=1:2',
  consumers: [],
  a11y: 'AA',
  lastIngested: '2026-05-19T00:00:00Z',
};

describe('generateMdx', () => {
  it('produces a kebab-case path from a PascalCase name', () => {
    const { path } = generateMdx(sampleMolecule);
    assert.equal(path, 'molecule/course-card.mdx');
  });

  it('uses the correct atomicLevel directory', () => {
    const { path } = generateMdx(sampleAtom);
    assert.equal(path, 'atom/button.mdx');
  });

  it('frontmatter contains all 11 schema fields', () => {
    const { content } = generateMdx(sampleMolecule);
    const fields = [
      'name',
      'atomicLevel',
      'status',
      'sourceMfe',
      'sourceRepo',
      'sourcePath',
      'version',
      'figmaCodeConnectUrl',
      'consumers',
      'a11y',
      'lastIngested',
    ];
    for (const field of fields) {
      assert.ok(
        content.includes(field),
        `Frontmatter should include field "${field}"`
      );
    }
  });

  it('frontmatter starts and ends with --- delimiters', () => {
    const { content } = generateMdx(sampleMolecule);
    assert.ok(content.startsWith('---\n'), 'Content should start with ---');
    // Second --- ends the frontmatter block
    const secondDash = content.indexOf('---\n', 4);
    assert.ok(secondDash > 4, 'Content should have a closing --- for frontmatter');
  });

  it('includes a Consumers section with bullet list when consumers are present', () => {
    const { content } = generateMdx(sampleMolecule);
    assert.ok(content.includes('## Consumers'), 'Should have Consumers heading');
    assert.ok(content.includes('- frontend-app-authoring'), 'Should list consumer 1');
    assert.ok(content.includes('- frontend-app-discussions'), 'Should list consumer 2');
  });

  it('shows "No registered consumers yet." when consumers array is empty', () => {
    const noConsumers: RegistryComponent = { ...sampleAtom, consumers: [] };
    const { content } = generateMdx(noConsumers);
    assert.ok(
      content.includes('No registered consumers yet.'),
      'Should show fallback text when no consumers'
    );
  });

  it('shows "Not yet linked to Figma." when figmaCodeConnectUrl is null', () => {
    const { content } = generateMdx(sampleMolecule);
    assert.ok(
      content.includes('Not yet linked to Figma.'),
      'Should show Figma fallback when URL is null'
    );
  });

  it('includes the Figma URL as a link when figmaCodeConnectUrl is set', () => {
    const { content } = generateMdx(sampleAtom);
    assert.ok(
      content.includes('https://figma.com/design/abc123?nodeId=1:2'),
      'Should include the Figma URL'
    );
    assert.ok(
      !content.includes('Not yet linked to Figma.'),
      'Should NOT show fallback when URL is present'
    );
  });

  it('includes the generator comment at the bottom', () => {
    const { content } = generateMdx(sampleMolecule);
    assert.ok(
      content.includes('{/* generated by @openedx-design-system/crawler */}'),
      'Should include generator comment'
    );
  });

  it('includes sourceRepo and sourcePath in the body', () => {
    const { content } = generateMdx(sampleMolecule);
    assert.ok(content.includes('openedx/frontend-app-learning'), 'Should include sourceRepo');
    assert.ok(content.includes('src/course-home/CourseCard.jsx'), 'Should include sourcePath');
  });

  it('includes status, a11y, version, lastIngested in the Status table', () => {
    const { content } = generateMdx(sampleMolecule);
    assert.ok(content.includes('stable'), 'Should include status value');
    assert.ok(content.includes('`AA`'), 'Should include a11y value');
    assert.ok(content.includes('`5.0.0`'), 'Should include version');
    assert.ok(content.includes('2026-05-19T00:00:00Z'), 'Should include lastIngested');
  });

  it('correctly kebab-cases multi-word PascalCase names', () => {
    const component: RegistryComponent = {
      ...sampleMolecule,
      name: 'CoursewareSearchResults',
      atomicLevel: 'organism',
    };
    const { path } = generateMdx(component);
    assert.equal(path, 'organism/courseware-search-results.mdx');
  });
});
