/**
 * End-to-end ingestion tests for src/ingest.ts
 *
 * Uses node:test, local fixtures, and a temporary directory.
 * No network calls are made.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, access } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { ingestAll } from '../src/ingest.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = resolve(__dirname, '..', '..', '..', 'registry', 'schema', 'component.schema.json');
const SOURCES_CONFIG = resolve(__dirname, '..', 'config', 'sources.json');

let tmpDir: string;

before(async () => {
  tmpDir = await mkdtemp(join(tmpdir(), 'ods-crawler-test-'));
});

after(async () => {
  if (tmpDir) {
    await rm(tmpDir, { recursive: true, force: true });
  }
});

describe('ingestAll (end-to-end with fixture)', () => {
  it('returns one result per source', async () => {
    const results = await ingestAll({
      sourcesConfig: SOURCES_CONFIG,
      outputDir: tmpDir,
      schemaPath: SCHEMA_PATH,
      fromFixtures: true,
    });

    assert.equal(results.length, 1, 'Should process exactly 1 fixture source');
  });

  it('writes exactly 5 MDX files for the learning MFE fixture', async () => {
    const results = await ingestAll({
      sourcesConfig: SOURCES_CONFIG,
      outputDir: tmpDir,
      schemaPath: SCHEMA_PATH,
      fromFixtures: true,
    });

    const result = results[0];
    assert.ok(result, 'Result should exist');
    assert.equal(result.components, 5, `Should write 5 components, got ${result.components}`);
    assert.equal(result.errors.length, 0, `Should have no errors. Got: ${result.errors.join(', ')}`);
  });

  it('creates MDX files at expected paths', async () => {
    await ingestAll({
      sourcesConfig: SOURCES_CONFIG,
      outputDir: tmpDir,
      schemaPath: SCHEMA_PATH,
      fromFixtures: true,
    });

    const expectedPaths = [
      join(tmpDir, 'page', 'courseware-search.mdx'),
      join(tmpDir, 'organism', 'course-tabs-navigation.mdx'),
      join(tmpDir, 'molecule', 'courseware-search-form.mdx'),
      join(tmpDir, 'organism', 'courseware-search-results.mdx'),
      join(tmpDir, 'molecule', 'course-tab-link.mdx'),
    ];

    for (const p of expectedPaths) {
      try {
        await access(p);
      } catch {
        assert.fail(`Expected MDX file to exist: ${p}`);
      }
    }
  });

  it('MDX output contains correct name in frontmatter', async () => {
    await ingestAll({
      sourcesConfig: SOURCES_CONFIG,
      outputDir: tmpDir,
      schemaPath: SCHEMA_PATH,
      fromFixtures: true,
    });

    const courseTabs = join(tmpDir, 'organism', 'course-tabs-navigation.mdx');
    const content = await readFile(courseTabs, 'utf-8');

    // YAML serializer emits string values with double-quotes; match accordingly.
    assert.ok(
      content.includes('name: "CourseTabsNavigation"') || content.includes("name: 'CourseTabsNavigation'") || content.includes('name: CourseTabsNavigation'),
      `Frontmatter should include name field with CourseTabsNavigation. Got:\n${content.slice(0, 400)}`
    );
  });

  it('MDX output for CourseTabsNavigation lists its consumer', async () => {
    await ingestAll({
      sourcesConfig: SOURCES_CONFIG,
      outputDir: tmpDir,
      schemaPath: SCHEMA_PATH,
      fromFixtures: true,
    });

    const courseTabs = join(tmpDir, 'organism', 'course-tabs-navigation.mdx');
    const content = await readFile(courseTabs, 'utf-8');

    assert.ok(
      content.includes('frontend-app-discussions'),
      'CourseTabsNavigation should list frontend-app-discussions as a consumer'
    );
  });

  it('MDX output includes the generator comment', async () => {
    await ingestAll({
      sourcesConfig: SOURCES_CONFIG,
      outputDir: tmpDir,
      schemaPath: SCHEMA_PATH,
      fromFixtures: true,
    });

    const courseSearch = join(tmpDir, 'page', 'courseware-search.mdx');
    const content = await readFile(courseSearch, 'utf-8');

    assert.ok(
      content.includes('{/* generated by @openedx-design-system/crawler */}'),
      'Generated MDX should include the generator comment'
    );
  });
});
